### ISSUE TITLE
Refactor manual error handling to use aws/dynamodb constants

### ISSUE THREAD

**Issue by brendanjryan** [vsco/domino#18]
In several spots we manually parse the error returned by the `aws/dynamodb` library. When possible we should use the [officially provided constants](https://godoc.org/github.com/aws/aws-sdk-go/service/dynamodb#ErrCodeConditionalCheckFailedException)

E.G. https://github.com/vsco/domino/blob/master/domino.go#L1622

**Comment by negator** [comment]
Done.

i.e. https://github.com/vsco/domino/blob/master/domino.go#L367

**Comment by brendanjryan** [comment]
🏹
